### ISSUE TITLE
TypeError: exception class/object expected from /app/config/netsuite.rb:22:in `raise'

### ISSUE THREAD

**Issue by jaahay** [NetSweet/netsuite#377]
```
Upsert.call([ns_invoice])
I, [2017-12-13T17:32:23.351768 #1974]  INFO -- : SOAP request: https://webservices.na1.netsuite.com/services/NetSuitePort_2014_1
I, [2017-12-13T17:32:23.351851 #1974]  INFO -- : SOAPAction: "upsert", Content-Type: text/xml;charset=UTF-8, Content-Length: 2663
D, [2017-12-13T17:32:23.352868 #1974] DEBUG -- : <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:platformMsgs="urn:messages_2014_1.platform.webservices.netsuite.com" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:platformCore="urn:core_2014_1.platform.webservices.netsuite.com" xmlns:platformCommon="urn:common_2014_1.platform.webservices.netsuite.com" xmlns:listRel="urn:relationships_2014_1.lists.webservices.netsuite.com" xmlns:tranSales="urn:sales_2014_1.transactions.webservices.netsuite.com" xmlns:tranPurch="urn:purchases_2014_1.transactions.webservices.netsuite.com" xmlns:actSched="urn:scheduling_2014_1.activities.webservices.netsuite.com" xmlns:setupCustom="urn:customization_2014_1.setup.webservices.netsuite.com" xmlns:listAcct="urn:accounting_2014_1.lists.webservices.netsuite.com" xmlns:tranBank="urn:bank_2014_1.transactions.webservices.netsuite.com" xmlns:tranCust="urn:customers_2014_1.transactions.webservices.netsuite.com" xmlns:tranEmp="urn:employees_2014_1.transactions.webservices.netsuite.com" xmlns:tranInvt="urn:inventory_2014_1.transactions.webservices.netsuite.com" xmlns:listSupport="urn:support_2014_1.lists.webservices.netsuite.com" xmlns:tranGeneral="urn:general_2014_1.transactions.webservices.netsuite.com" xmlns:commGeneral="urn:communication_2014_1.general.webservices.netsuite.com" xmlns:listMkt="urn:marketing_2014_1.lists.webservices.netsuite.com" xmlns:listWebsite="urn:website_2014_1.lists.webservices.netsuite.com" xmlns:fileCabinet="urn:filecabinet_2014_1.documents.webservices.netsuite.com" xmlns:listEmp="urn:employees_2014_1.lists.webservices.netsuite.com">
  <env:Header>
    <platformMsgs:passport>
      <platformCore:account>...</platformCore:account>
      <platformCore:email>...</platformCore:email>
      <platformCore:password>...</platformCore:password>
      <platformCore:role internalId=.../>
    </platformMsgs:passport>
  </env:Header>
  <env:Body>
    <platformMsgs:upsert>
      <platformMsgs:record xsi:type="tranSales:Invoice" platformMsgs:externalId=...>
        <tranSales:tranDate>2017-12-31T23:59:59+00:00</tranSales:tranDate>
        <tranSales:startDate>2017-12-31T23:59:59+00:00</tranSales:startDate>
        <tranSales:dueDate>2018-01-30T23:59:59+00:00</tranSales:dueDate>
        <tranSales:endDate>2018-01-30T23:59:59+00:00</tranSales:endDate>
        <tranSales:memo>...</tranSales:memo>
        <tranSales:otherRefNum xsi:nil="true"/>
        <tranSales:entity internalId=... externalId=... type="customer"/>
      </platformMsgs:record>
    </platformMsgs:upsert>
  </env:Body>
</env:Envelope>

D, [2017-12-13T17:32:23.353776 #1974] DEBUG -- : HTTPI POST request to webservices.na1.netsuite.com (net_http)
I, [2017-12-13T17:32:24.052819 #1974]  INFO -- : SOAP response (status 200)
D, [2017-12-13T17:32:24.053363 #1974] DEBUG -- : <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Header>
    <platformMsgs:documentInfo xmlns:platformMsgs="urn:messages_2014_1.platform.webservices.netsuite.com">
      <platformMsgs:nsId>...</platformMsgs:nsId>
    </platformMsgs:documentInfo>
  </soapenv:Header>
  <soapenv:Body>
    <upsertResponse xmlns="urn:messages_2014_1.platform.webservices.netsuite.com">
      <writeResponse>
        <platformCore:status xmlns:platformCore="urn:core_2014_1.platform.webservices.netsuite.com" isSuccess="false">
          <platformCore:statusDetail type="ERROR">
            <platformCore:code>USER_ERROR</platformCore:code>
            <platformCore:message>You must enter at least one line item for this transaction.</platformCore:message>
          </platformCore:statusDetail>
        </platformCore:status>
        <baseRef xmlns:platformCore="urn:core_2014_1.platform.webservices.netsuite.com" externalId=... type="invoice" xsi:type="platformCore:RecordRef"/>
      </writeResponse>
    </upsertResponse>
  </soapenv:Body>
</soapenv:Envelope>

TypeError: exception class/object expected
from /app/config/netsuite.rb:22:in `raise'
```

**Comment by iloveitaly** [comment]
@jaahay can you provide full context around this issue—what does the upstread NS code look like?
