### ISSUE TITLE
wrong number of arguments (given 1, expected 0) when searching for Account

### ISSUE THREAD

**Issue by ericcj** [NetSweet/netsuite#522]
is there an easier way to get accounts by number than this?  it seems like a simple search but i haven't tracked down what result_class it's trying to initialize that takes no arguments...

```
NetSuite::Records::Account.search({
  basic: [
    {
      field: 'number',
      operator: 'is',
      value: 4508
    }
  ]
})

ArgumentError: wrong number of arguments (given 1, expected 0)
	from /usr/share/rvm/gems/ruby-2.4.10/bundler/gems/netsuite-f1a7968d9330/lib/netsuite/support/search_result.rb:47:in `initialize'
	from /usr/share/rvm/gems/ruby-2.4.10/bundler/gems/netsuite-f1a7968d9330/lib/netsuite/support/search_result.rb:47:in `new'
	from /usr/share/rvm/gems/ruby-2.4.10/bundler/gems/netsuite-f1a7968d9330/lib/netsuite/support/search_result.rb:47:in `block in initialize'
	from /usr/share/rvm/gems/ruby-2.4.10/bundler/gems/netsuite-f1a7968d9330/lib/netsuite/support/search_result.rb:46:in `each'
	from /usr/share/rvm/gems/ruby-2.4.10/bundler/gems/netsuite-f1a7968d9330/lib/netsuite/support/search_result.rb:46:in `initialize'
	from /usr/share/rvm/gems/ruby-2.4.10/bundler/gems/netsuite-f1a7968d9330/lib/netsuite/actions/search.rb:247:in `new'
	from /usr/share/rvm/gems/ruby-2.4.10/bundler/gems/netsuite-f1a7968d9330/lib/netsuite/actions/search.rb:247:in `search'

**Comment by iloveitaly** [comment]
@ericcj unfortunately, this is the best way. My guess is there is a permission error or something wrong with the response. Turn on NS logging to debug it further.

Check out the slack community if you need more help!

**Comment by ericcj** [comment]
the response looks ok:  

```
          <platformCore:record xmlns:listAcct="urn:accounting_2021_1.lists.webservices.netsuite.com" internalId="355" xsi:type="listAcct:Account">
            <listAcct:acctType>_costOfGoodsSold</listAcct:acctType>
            <listAcct:acctNumber>4508</listAcct:acctNumber>
            <listAcct:acctName>Selling Fees/Commissions - COS</listAcct:acctName>
            <listAcct:includeChildren>false</listAcct:includeChildren>
            <listAcct:generalRate>_average</listAcct:generalRate>
            <listAcct:parent internalId="246">
              <platformCore:name>4500 Cost of Sales</platformCore:name>
            </listAcct:parent>
            <listAcct:cashFlowRate>_average</listAcct:cashFlowRate>
            <listAcct:isInactive>false</listAcct:isInactive>
            <listAcct:inventory>false</listAcct:inventory>
            <listAcct:revalue>false</listAcct:revalue>
            <listAcct:customFieldList>
              <platformCore:customField internalId="3602" scriptId="custrecord_cps_bdc_lastupdatedbyimp_acc" xsi:type="platformCore:BooleanCustomFieldRef">
                <platformCore:value>false</platformCore:value>
              </platformCore:customField>
              <platformCore:customField internalId="3609" scriptId="custrecord_cps_bdc_updatedbyimp_acc" xsi:type="platformCore:BooleanCustomFieldRef">
                <platformCore:value>false</platformCore:value>
              </platformCore:customField>
              <platformCore:customField internalId="1145" scriptId="custrecord_has_mx_localization" xsi:type="platformCore:BooleanCustomFieldRef">
                <platformCore:value>false</platformCore:value>
              </platformCore:customField>
            </listAcct:customFieldList>
          </platformCore:record>

**Comment by iloveitaly** [comment]
@ericcj my guess is this might be a rugby 2.4 thing. I wrote up a test case for this and it's passing: https://github.com/NetSweet/netsuite/commit/197d4e63e85d6a9fcd0ee0d45a1ee8a8b0ece05c
